### ISSUE TITLE
Problem with compiling the Mex file

### ISSUE THREAD

**Issue by AnisHasanpour** [alddiaz/MATLAB_AprilTag3#1]
Hello everyone,

I've tired to compile Apriltag in Matlab for Linux. However, there are several error messages and I assume that some of the functions such as "black border" are not compatible with Matlab. I would be grateful if you have any idea to solve this issue.
Thanks,

**Comment by alddiaz** [comment]
Answer sent by email!

**Comment by alddiaz** [comment]
Your welcome :)
I hope you get to have the detector working in Linux!

Would you mind letting me know what kind of research project you are
conducting by using AprilTags in your field?
